apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: db
spec:
  serviceName: "db"  # Must be defined even if not exposed
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      imagePullSecrets:
      - name: redhat-auth
      containers:
      - name: postgres
        image: registry.redhat.io/rhel9/postgresql-15
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: redhatocp
        #- name: POSTGRESQL_USER
        #  value: postgres
        #- name: POSTGRESQL_PASSWORD
        #  value: postgres
        #- name: POSTGRESQL_DATABASE
        #  value: db
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-nfs
          mountPath: /var/lib/pgsql/data
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      volumes:
      - name: db-nfs
        persistentVolumeClaim:
          claimName: db-nfs
  volumeClaimTemplates:
    - metadata:
        name: db-nfs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: nfs-storage
        volumeMode: Filesystem

