apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      imagePullSecrets:
      - name: docker-auth
      containers:
      - image: docker.io/minsiktruong/votingapp-result:latest
        imagePullPolicy: Always
        name: result
        resources:
          requests:
            cpu: 1m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 60Mi
        ports:
        - containerPort: 8081
          name: result

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: result-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 50Mi
