apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: docker-auth
      containers:
      - image: docker.io/minsiktruong/votingapp-worker:latest
        imagePullPolicy: Always
        name: worker
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 100m
            memory: 100Mi

---

#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: worker-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: worker
#  minReplicas: 2
#  maxReplicas: 5
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: AverageValue
#        averageValue: 80m
#
#---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: worker-vpa
spec: 
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: ["cpu", "memory"]
      minAllowed:
        cpu: 10m
        memory: 30Mi
      maxAllowed:
        cpu: 300m
        memory: 300Mi 
